import React, { FC } from 'react'
import { NavBar } from '../NavBar'
import { Head } from 'next/document'
import styles from './MainLayout.module.css'

export const MainLayout: FC = ({ children }) => {
  return (
    <div className={styles.container}>
        <Head>
            <title>Home - Tobi</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <NavBar />
        <main className={styles.main}>
            {children}
        </main>
    </div>
  )
}
